# Generated by Django 3.0.5 on 2020-04-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avance', models.DateField()),
                ('desc_avance', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['fecha_avance'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('departamento', models.CharField(max_length=30, null=True)),
                ('ciudad', models.CharField(max_length=50, null=True, verbose_name='Ciudad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_apertura', models.DateField()),
                ('estado_siebel', models.CharField(blank=True, max_length=10)),
                ('grupo', models.CharField(blank=True, max_length=10, null=True)),
                ('asunto_correo', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(blank=True, max_length=30)),
                ('nombre_obra', models.CharField(blank=True, max_length=30)),
                ('consorcio', models.CharField(blank=True, max_length=30)),
                ('arpu', models.CharField(blank=True, max_length=30)),
                ('avance', models.ManyToManyField(blank=True, to='seguimiento.Avances', verbose_name='Avance')),
                ('tipo_seguimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Tipo_seguimiento', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['numero_seguimiento'],
            },
        ),
    ]
