# Generated by Django 3.0.5 on 2020-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='avance',
        ),
        migrations.AddField(
            model_name='avances',
            name='seguimiento',
            field=models.ManyToManyField(blank=True, to='seguimiento.Seguimiento', verbose_name='Avance'),
        ),
    ]
