# Generated by Django 3.0.5 on 2020-04-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20200418_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_seguimiento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
