# Generated by Django 3.0.5 on 2020-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_tipo_seguimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
